import type { BookEntry } from "@/types";

export const MOCK_BOOKS: BookEntry[] = [
  {
    id: "mock-1",
    type: "friend",
    title: "To Ceci, With Stars",
    authorLabel: "Luna",
    avatarUrl: undefined,
    coverTheme: "lavender",
    spineLabel: "Luna's Letter",
    body: "You taught me that the best kind of friendship is the one where you can sit in silence and still feel like you've had the best conversation of your life. I'll carry that with me wherever I go. Thank you for being my constant in a world full of variables.",
    images: [],
    reactionStyle: "whisper-fade",
    createdAt: "2026-03-15T10:00:00Z",
    isFeatured: true,
  },
  {
    id: "mock-2",
    type: "friend",
    title: "Remember That Time",
    authorLabel: "Marco",
    avatarUrl: undefined,
    coverTheme: "sage",
    spineLabel: "Marco",
    body: "Remember when we tried to cook that ridiculous recipe at 2am and nearly set off the fire alarm? Or when we got lost in that tiny town and ended up finding the best coffee shop in the world? Every adventure with you has been worth every wrong turn. Keep being brilliantly unpredictable.",
    images: [],
    reactionStyle: "ink-bloom",
    createdAt: "2026-03-20T14:30:00Z",
    isFeatured: true,
  },
  {
    id: "mock-3",
    type: "wiki",
    title: "Friendship",
    authorLabel: "Wikipedia",
    coverTheme: "sky",
    spineLabel: "Friendship",
    body: "Friendship is a relationship of mutual affection between people. It is a stronger form of interpersonal bond than an acquaintance or an association, such as a classmate, neighbor, coworker, or colleague. Friendship has been studied in academic fields such as communication, sociology, social psychology, anthropology, and philosophy.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Friendship",
    images: [],
    reactionStyle: "warm-highlight",
    createdAt: "2026-03-01T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "mock-4",
    type: "friend",
    title: "A Small World",
    authorLabel: "Sofia",
    avatarUrl: undefined,
    coverTheme: "rose",
    spineLabel: "Sofia",
    body: "The world got so much bigger when I met you, and somehow also so much smaller. Like suddenly there was someone who understood the strange little things I never knew how to explain. You made the ordinary feel extraordinary. I hope you always know how rare that is.",
    images: [],
    reactionStyle: "memory-dust",
    createdAt: "2026-03-25T09:00:00Z",
    isFeatured: true,
  },
];
