import type { BookEntry } from "@/types";

export const MOCK_BOOKS: BookEntry[] = [
  {
    id: "wiki-friendship",
    type: "wiki",
    title: "Friendship",
    authorLabel: "Wikipedia",
    coverTheme: "burgundy",
    spineLabel: "Friendship",
    body: "Friendship is a relationship of mutual affection between people. It is a stronger form of interpersonal bond than an acquaintance or an association, such as a classmate, neighbor, coworker, or colleague. Friendship has been studied in academic fields such as communication, sociology, social psychology, anthropology, and philosophy. Various academic theories of friendship have been proposed, including social exchange theory, equity theory, relational dialectics, and attachment styles. Although there are many forms of friendship, some of which may vary from place to place, certain characteristics are present in many such bonds. Such features include choosing to be with one another, enjoying time spent together, and being able to engage in a positive and supportive role to one another. In some cases, the term 'platonic relationship' is used to describe a friendship that exists without physical or romantic intimacy. The understanding of friendship in children tends to be more heavily focused on areas such as common activities, physical proximity, and shared expectations. These friendships provide opportunity for playing and practicing self-regulation. Most children tend to describe friendship in terms of things like sharing, and children are more likely to share with someone they consider to be a friend. As children mature, they become less individualized and are more aware of others. They gain the ability to empathize with their friends, and enjoy playing in larger groups. They also experience peer rejection as they move through the middle childhood years. By the time a child reaches the age of twelve, most have developed a concept of friendship that includes aspects of trust, loyalty, mutual support, and the ability to communicate openly about one's feelings.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Friendship",
    images: [],
    reactionStyle: "warm-highlight",
    createdAt: "2026-03-01T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-aurora",
    type: "wiki",
    title: "Aurora Borealis",
    authorLabel: "Wikipedia",
    coverTheme: "navy",
    spineLabel: "Aurora",
    body: "An aurora, also commonly known as the northern lights (aurora borealis) or southern lights (aurora australis), is a natural light display in Earth's sky, predominantly seen in high-latitude regions. Auroras display dynamic patterns of brilliant lights that appear as curtains, rays, spirals, or dynamic flickers covering the entire sky. They are the result of disturbances in the Earth's magnetosphere caused by the solar wind. Major disturbances result from enhancements in the speed of the solar wind from coronal holes and coronal mass ejections. These disturbances alter the trajectories of charged particles in the magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere where their energy is lost. The resulting ionization and excitation of atmospheric constituents emit light of varying colour and complexity. The form of the aurora, occurring within bands around both polar regions, is also dependent on the amount of acceleration imparted to the precipitating particles. Most aurorae occur in a band known as the auroral zone, which is typically 3° to 6° wide in latitude and between 10° and 20° from the geomagnetic poles at all local times. During a geomagnetic storm, the auroral zone expands to lower latitudes. Auroral arcs can be very thin, sometimes only 100 metres wide when seen from the side, while extending over great distances. Diffuse aurora are similar to thin curtains and can reach heights of 600 kilometres above the surface. Even though auroral emissions occur at altitudes above those reached by balloons and most aircraft, these emissions are occasionally seen on the ground.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Aurora",
    images: [],
    reactionStyle: "memory-dust",
    createdAt: "2026-03-02T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-coffee",
    type: "wiki",
    title: "History of Coffee",
    authorLabel: "Wikipedia",
    coverTheme: "cognac",
    spineLabel: "Coffee",
    body: "The history of coffee dates back to centuries of old oral tradition in modern-day Ethiopia and Yemen. It was already known in Mecca in the 15th century. Also, in the 15th century, Sufi monasteries in Yemen employed coffee as an aid to concentration during prayers. Coffee later spread to the Levant in the early 16th century; it caused some controversy on whether it was halal in Ottoman and Mamluk society. Coffee arrived in Italy the second half of the 16th century through commercial Mediterranean trade routes, while Central and Eastern Europeans learnt of coffee from the Ottomans. By the mid 17th century, it had reached the rest of Europe, then to Southeast Asia and then to the Americas. The first coffeehouse in England was set up in Oxford in 1652 and spread rapidly across Europe. Coffeehouses in the 17th and 18th centuries were popular places for intellectual exchange, business transactions, and socializing. In the Ottoman Empire, coffeehouses were known as 'schools of the wise' and served as centers of political discussion. The Dutch were the first Europeans to obtain live coffee trees, which they cultivated in their colonies. In the early 18th century, a young French naval officer managed to transport a seedling to the Caribbean island of Martinique, from which much of the world's cultivated coffee descends. By the 18th century, coffee had become one of the world's most profitable export crops. Today, coffee is one of the most widely consumed beverages in the world, with over two billion cups consumed every day across more than seventy countries.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_coffee",
    images: [],
    reactionStyle: "ink-bloom",
    createdAt: "2026-03-03T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-origami",
    type: "wiki",
    title: "Origami",
    authorLabel: "Wikipedia",
    coverTheme: "ivory",
    spineLabel: "Origami",
    body: "Origami is the Japanese art of paper folding. In modern usage, the word 'origami' is often used as an inclusive term for all folding practices, regardless of their culture of origin. The goal is to transform a flat square sheet of paper into a finished sculpture through folding and sculpting techniques. Modern origami practitioners generally discourage the use of cuts, glue, or markings on the paper. The small number of basic origami folds can be combined in a variety of ways to make intricate designs. The best-known origami model is the Japanese paper crane. In general, these designs begin with a square sheet of paper whose sides may be of different colors, prints, or patterns. Traditional Japanese origami, which has been practiced since the Edo Period (1603\u20131867), has often been less strict about these conventions, sometimes cutting the paper or using nonsquare shapes to start with. The principles of origami are also used in stents, packaging, and other engineering applications. The practice and study of origami encapsulates several subjects of mathematical interest. For instance, flat-foldability, whether a crease pattern can be folded into a two-dimensional model, has been a topic of considerable mathematical study. A number of technological advances have come from insights obtained through paper folding. In the field of space engineering, origami-inspired designs have been used to develop deployable solar panels and satellite antennas. Medical applications include origami-based stent designs that can be folded small enough to navigate through blood vessels and then expanded at the target site.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Origami",
    images: [],
    reactionStyle: "paper-ripple",
    createdAt: "2026-03-04T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-reef",
    type: "wiki",
    title: "Great Barrier Reef",
    authorLabel: "Wikipedia",
    coverTheme: "forest",
    spineLabel: "The Reef",
    body: "The Great Barrier Reef is the world's largest coral reef system, composed of over 2,900 individual reefs and 900 islands stretching for over 2,300 kilometres over an area of approximately 344,400 square kilometres. The reef is located in the Coral Sea, off the coast of Queensland, Australia. The Great Barrier Reef can be seen from outer space and is the world's biggest single structure made by living organisms. This reef structure is composed of and built by billions of tiny organisms, known as coral polyps. It supports a wide diversity of life and was selected as a World Heritage Site in 1981. CNN labelled it one of the seven natural wonders of the world. The Queensland National Trust named it a state icon of Queensland. A large part of the reef is protected by the Great Barrier Reef Marine Park, which helps to limit the impact of human use, such as fishing and tourism. Other environmental pressures on the reef and its ecosystem include runoff water quality, climate change accompanied by mass coral bleaching, and cyclic population outbreaks of the crown-of-thorns starfish. The reef supports an extraordinary diversity of life, including many vulnerable or endangered species, some of which may be endemic to the reef system. Thirty species of whales, dolphins, and porpoises have been recorded in the Great Barrier Reef, including the dwarf minke whale, Indo-Pacific humpback dolphin, and the humpback whale. Large populations of dugongs live there. Six species of sea turtles come to the reef to breed, and it is home to over 1,500 species of fish.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Great_Barrier_Reef",
    images: [],
    reactionStyle: "whisper-fade",
    createdAt: "2026-03-05T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-jazz",
    type: "wiki",
    title: "Jazz",
    authorLabel: "Wikipedia",
    coverTheme: "plum",
    spineLabel: "Jazz",
    body: "Jazz is a music genre that originated in the African-American communities of New Orleans, Louisiana, in the late 19th and early 20th centuries, with its roots in blues, ragtime, European harmony and African rhythmic rituals. Since the 1920s Jazz Age, it has been recognized as a major form of musical expression in traditional and popular music. Jazz is characterized by swing and blue notes, complex chords, call-and-response vocals, polyrhythms and improvisation. Jazz has roots in European harmony and African rhythmic rituals. As jazz spread around the world, it drew on national, regional, and local musical cultures, which gave rise to different styles. New Orleans jazz began in the early 1910s, combining earlier brass band marches, French quadrilles, biguine, ragtime and blues with collective polyphonic improvisation. In the 1930s, heavily arranged dance-oriented swing big bands, Kansas City jazz, and gypsy jazz were prominent styles. Bebop emerged in the 1940s, shifting jazz from danceable popular music toward a more challenging 'musician's music' which was played at faster tempos and used more chord-based improvisation. Cool jazz developed near the end of the 1940s, introducing calmer, smoother sounds. Free jazz and the related avant-garde emerged in the 1950s and 1960s, exploring playing without regular meter, beat, or formal structures. Jazz-rock fusion appeared in the late 1960s and early 1970s, combining jazz improvisation with rock music's electric instruments and amplified sound. In the 1980s, a commercial form of jazz fusion called smooth jazz became successful and gained significant radio airplay.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Jazz",
    images: [],
    reactionStyle: "typewriter-echo",
    createdAt: "2026-03-06T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-pompeii",
    type: "wiki",
    title: "Pompeii",
    authorLabel: "Wikipedia",
    coverTheme: "charcoal",
    spineLabel: "Pompeii",
    body: "Pompeii was an ancient city located in what is now the comune of Pompei near Naples in the Campania region of Italy. Pompeii, along with Herculaneum and many villas in the surrounding area, was buried under 4 to 6 metres of volcanic ash and pumice in the eruption of Mount Vesuvius in AD 79. Largely preserved under the ash, the excavated city offered a unique snapshot of Roman life, frozen at the moment it was buried and providing an extraordinarily detailed insight into the everyday life of its inhabitants. It was a wealthy town of 11,000 inhabitants, enjoying many fine public buildings and luxurious private houses with lavish decorations, furnishings and works of art which were the main attractions for the early excavators. Organic remains, including wooden objects and human bodies, were interred in the ash andite preserved in remarkable detail. The eruption destroyed the city in two phases: first, the eruption rained tephra and pumice on Pompeii, burying the city under about 2.8 metres; and second, pyroclastic flows reached the city walls and incinerated or suffocated any remaining inhabitants. Buildings were damaged or destroyed by falling pumice stones and collapsing roofs. The site was lost for about 1,500 years until its rediscovery in 1599 and broader rediscovery in 1748. Since then, its excavation has provided extraordinary insight into the culture of a city at the height of the Roman Empire. Today, it is one of the most popular tourist attractions in Italy, with approximately 2.5 million visitors every year.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Pompeii",
    images: [],
    reactionStyle: "folded-light",
    createdAt: "2026-03-07T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-honeybee",
    type: "wiki",
    title: "Honey Bee",
    authorLabel: "Wikipedia",
    coverTheme: "moss",
    spineLabel: "Honey Bee",
    body: "A honey bee is a eusocial flying insect within the genus Apis of the bee clade, all native to mainland Afro-Eurasia. After bees spread naturally throughout Africa and Eurasia, humans became responsible for the current cosmopolitan distribution of honey bees, introducing several subspecies into South America, North America, and Australia. Honey bees are known for their construction of perennial colonial nests from wax, the large size of their colonies, and surplus production and storage of honey, distinguishing their hives as a prized foraging target of many animals, including honey badgers, bears, and human hunter-gatherers. Only eight surviving species of honey bee are recognized, with a total of 43 subspecies. Honey bees represent only a small fraction of the roughly 20,000 known species of bees. The best known honey bee is the western honey bee, which has been domesticated for honey production and crop pollination. It is the only domesticated species of bee. Honey bees build their nests out of wax, arranging the hexagonal cells so that they share walls, which saves on material. The honeycomb structure is remarkably efficient at storing honey and pollen while using the minimum amount of wax. A single colony can contain between 20,000 and 80,000 bees. Worker bees perform many tasks including foraging for nectar and pollen, nursing young larvae, building comb, and defending the hive. The queen's sole function is to lay eggs, while drones exist primarily to mate with queens from other colonies. Honey bees communicate through a sophisticated system of dances and pheromones, with the famous waggle dance being used to convey the direction and distance of food sources.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Honey_bee",
    images: [],
    reactionStyle: "star-margin",
    createdAt: "2026-03-08T00:00:00Z",
    isFeatured: false,
  },
];
