import type { BookEntry } from "@/types";

export const MOCK_BOOKS: BookEntry[] = [
  {
    id: "wiki-friendship",
    type: "wiki",
    title: "Friendship",
    authorLabel: "Wikipedia",
    coverTheme: "sky",
    spineLabel: "Friendship",
    body: "Friendship is a relationship of mutual affection between people. It is a stronger form of interpersonal bond than an acquaintance or an association, such as a classmate, neighbor, coworker, or colleague. Friendship has been studied in academic fields such as communication, sociology, social psychology, anthropology, and philosophy. Various academic theories of friendship have been proposed, including social exchange theory, equity theory, relational dialectics, and attachment styles. Although there are many forms of friendship, some of which may vary from place to place, certain characteristics are present in many such bonds. Such features include choosing to be with one another, enjoying time spent together, and being able to engage in a positive and supportive role to one another.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Friendship",
    images: [],
    reactionStyle: "warm-highlight",
    createdAt: "2026-03-01T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-stars",
    type: "wiki",
    title: "Star",
    authorLabel: "Wikipedia",
    coverTheme: "lavender",
    spineLabel: "Stars",
    body: "A star is a luminous spheroid of plasma held together by self-gravity. The nearest star to Earth is the Sun. Many other stars are visible to the naked eye at night; their immense distances from Earth make them appear as fixed points of light. The most prominent stars have been categorised into constellations and asterisms, and many of the brightest stars have proper names. Astronomers have assembled star catalogues that identify the known stars and provide standardized stellar designations. The observable universe contains an estimated 10^22 to 10^24 stars. Only about 4,000 of these stars are visible to the naked eye — all within the Milky Way galaxy.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Star",
    images: [],
    reactionStyle: "memory-dust",
    createdAt: "2026-03-02T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-london",
    type: "wiki",
    title: "London",
    authorLabel: "Wikipedia",
    coverTheme: "slate",
    spineLabel: "London",
    body: "London is the capital and largest city of both England and the United Kingdom, with a population of around 8.8 million. It stands on the River Thames in south-east England, at the head of its 50-mile estuary leading to the North Sea. London has been a major settlement for two millennia, and was originally called Londinium, which was founded by the Romans. The City of London, its ancient core and financial centre, was founded by the Romans as Londinium and retains boundaries close to its medieval ones. The City of Westminster, to the west of the City of London, has for centuries hosted the national government and parliament.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/London",
    images: [],
    reactionStyle: "folded-light",
    createdAt: "2026-03-03T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-mycology",
    type: "wiki",
    title: "Mycology",
    authorLabel: "Wikipedia",
    coverTheme: "sage",
    spineLabel: "Fungi",
    body: "Mycology is the branch of biology concerned with the study of fungi, including their taxonomy, genetics, biochemical properties, and use by humans. Fungi can be a source of tinder, food, traditional medicine, and entheogens, as well as sources of certain toxic compounds. The field of phytopathology, the study of plant diseases, is closely related because many plant pathogens are fungi. A biologist specializing in mycology is called a mycologist. Mycology branches into the field of phytopathology, the study of plant diseases, which is of enormous importance since the great majority of plant pathogens are fungi.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Mycology",
    images: [],
    reactionStyle: "ink-bloom",
    createdAt: "2026-03-04T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "wiki-constellation",
    type: "wiki",
    title: "Constellation",
    authorLabel: "Wikipedia",
    coverTheme: "amber",
    spineLabel: "Constellations",
    body: "A constellation is an area on the celestial sphere in which a group of visible stars forms a perceived pattern or outline, typically representing an animal, mythological subject, or inanimate object. The origins of the earliest constellations likely go back to prehistory. People used them to relate stories of their beliefs, experiences, creation, or mythology. Different cultures and countries adopted their own constellations, some of which lasted into the early 20th century before today's constellations were internationally recognized. Adoption of constellations has changed significantly over time.",
    sourceLabel: "Wikipedia",
    sourceUrl: "https://en.wikipedia.org/wiki/Constellation",
    images: [],
    reactionStyle: "star-margin",
    createdAt: "2026-03-05T00:00:00Z",
    isFeatured: false,
  },
  {
    id: "friend-luna",
    type: "friend",
    title: "To Ceci, With Stars",
    authorLabel: "Luna",
    avatarUrl: undefined,
    coverTheme: "rose",
    spineLabel: "Luna's Letter",
    body: "You taught me that the best kind of friendship is the one where you can sit in silence and still feel like you've had the best conversation of your life. I'll carry that with me wherever I go. Thank you for being my constant in a world full of variables. Every star in the sky reminds me of the light you bring to everyone around you.",
    images: [],
    reactionStyle: "whisper-fade",
    createdAt: "2026-03-15T10:00:00Z",
    isFeatured: true,
  },
];
